/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practicaFinal;

import java.awt.Component;
import java.io.File;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.Player;
import javax.media.bean.playerbean.MediaPlayer;

/**
 * Ventana que hereda de <code>JInternalFrame</code> y define los métodos 
 * necesarios para la reproducción de audio mediante la biblioteca JMF.
 * @author Rogelio Gil García
 * @version 1.0
 */
public class VentanaInternaSonido extends javax.swing.JInternalFrame {
    private Player p = new MediaPlayer();
    
    /**
     * Constructor privado para la ventana de reproducción de audio. 
     * El uso de un constructor estándar implicaría siempre la creación de la 
     * ventana interna, por lo que se usa la definición de un método 
     * <code>getInstance(File f)</code> que llame internamente al constructor.
     * @param f Fichero de audio a reproducir.
     */
    private VentanaInternaSonido(File f) {
        initComponents();
        try{
            MediaLocator ml = new MediaLocator("file:"+f.getAbsolutePath());
            p = Manager.createRealizedPlayer(ml); 
            /* Component  areaVisual = p.getVisualComponent(); 
            if(areaVisual!=null) this.add(areaVisual,java.awt.BorderLayout.CENTER);  */
            Component  panelControl = p.getControlPanelComponent(); 
            panelControl.setBounds(0, 0, 510, 40);
            if(panelControl!=null) this.add(panelControl,java.awt.BorderLayout.SOUTH);  
            this.pack(); 
        }catch(Exception e){System.err.println("Error al crear la ventana de sonido");}
    }

    /**
     * Método que devuelve la instancia de la clase.
     * Este método llama internamiente al constructor.
     * @param f Fichero a reproducir.
     * @return devuelve la instancia que crea el constructor.
     */
    public static VentanaInternaSonido getInstance(File f){
        VentanaInternaSonido v= new VentanaInternaSonido(f);
        return v.p!=null?v:null;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(2000, 2000));
        setMinimumSize(new java.awt.Dimension(300, 30));
        setPreferredSize(new java.awt.Dimension(520, 60));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        p.stop();
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        p.start();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
