

package practicaFinal;

import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.media.Buffer;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.Player;
import javax.media.bean.playerbean.MediaPlayer;
import javax.media.control.FrameGrabbingControl;
import javax.media.format.VideoFormat;
import javax.media.util.BufferToImage;



/**
 * Ventana que hereda de <code>JInternalFrame</code> y define los métodos 
 * necesarios para la reproducción de vídeo mediante la biblioteca JMF.
 * @author Rogelio Gil García
 * @version 1.0
 */
public class VentanaInternaVideo extends javax.swing.JInternalFrame {
    private Player p = new MediaPlayer();
    
    
    /**
     * Constructor privado para la ventana de reproducción de vídeo. 
     * El uso de un constructor estándar implicaría siempre la creación de la 
     * ventana interna, por lo que se usa la definición de un método 
     * <code>getInstance(File f)</code> que llame internamente al constructor.
     * @param f Fichero de audio a reproducir.
     */
    private VentanaInternaVideo(File f) {
        initComponents();
        try{
            MediaLocator ml = new MediaLocator("file:"+f.getAbsolutePath());
            p = Manager.createRealizedPlayer(ml);
            Component  areaVisual = p.getVisualComponent();
            if(areaVisual!=null) this.add(areaVisual,java.awt.BorderLayout.CENTER);
            Component  panelControl = p.getControlPanelComponent();
            if(panelControl!=null) this.add(panelControl,java.awt.BorderLayout.SOUTH);
            this.pack();
        }catch(Exception e){System.err.println("Error al crear la ventana de vídeo");}
    }

    /**
     * Método que devuelve la instancia de la clase.
     * Este método llama internamiente al constructor.
     * @param f Fichero a reproducir.
     * @return devuelve la instancia que crea el constructor.
     */
    public static VentanaInternaVideo getInstance(File f){
        VentanaInternaVideo v= new VentanaInternaVideo(f);
        return v.p!=null?v:null;
    }
    
    
    /**
     * Métodoo para capturar una imagen de una ventana tanto en reproducción
     * de vídeo como de una ventana webcam.
     * @return Imagen capturada.
     */
    public BufferedImage getFrame(){
        FrameGrabbingControl fgc;
        String claseCtr = "javax.media.control.FrameGrabbingControl";
        fgc = (FrameGrabbingControl)p.getControl(claseCtr );
        Buffer bufferFrame = fgc.grabFrame();
        BufferToImage bti;
        bti=new BufferToImage((VideoFormat)bufferFrame.getFormat());
        Image img = bti.createImage(bufferFrame);
        return (BufferedImage)img;
    }
    

        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        p.stop();
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        p.start();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
