/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practicaFinal;

import java.io.File;
import sm.sound.SMRecorder;
import sm.sound.SMSoundPlayerRecorder;

/**
 * Ventana que hereda de <code>JInternalFrame</code> y define los métodos 
 * necesarios para la grabación de audio mediante la biblioteca SM.
 * @author Rogelio Gil García
 * @version 1.0
 */
public class VentanaInternaGrabador extends javax.swing.JInternalFrame {
    SMRecorder recorder;
    
    /**
     * Constructor para la ventana de grabación de audio.
     * @param f Fichero donde guardaremos el audio grabado.
     */
    public VentanaInternaGrabador(File f) {
        initComponents();
        recorder = new SMSoundPlayerRecorder(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gGrabador = new javax.swing.ButtonGroup();
        record = new javax.swing.JToggleButton();
        stop = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridLayout());

        record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSonido/RecordPressed_48x48.png"))); // NOI18N
        record.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSonido/RecordDisabled_48x48.png"))); // NOI18N
        record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordActionPerformed(evt);
            }
        });
        getContentPane().add(record);

        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSonido/StopNormalRed_48x48.png"))); // NOI18N
        stop.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosSonido/StopDisabled_48x48.png"))); // NOI18N
        stop.setEnabled(false);
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        getContentPane().add(stop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordActionPerformed
        if(recorder!=null) recorder.record();
        record.setEnabled(false);
        stop.setEnabled(true);
    }//GEN-LAST:event_recordActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        if(recorder!=null) recorder.stop();
        stop.setEnabled(false);
        record.setEnabled(true);
    }//GEN-LAST:event_stopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup gGrabador;
    private javax.swing.JToggleButton record;
    private javax.swing.JToggleButton stop;
    // End of variables declaration//GEN-END:variables
}
